language: go
dist: xenial
sudo: false
services:
  - docker
env:
  matrix:
    - GO111MODULE=on
matrix:
  allow_failures:
  include:
    - os: linux
      go: 1.12.x
      cache:
        directories:
          - "/home/travis/.cache/go-build"
    - os: osx
      go: 1.12.x
      cache:
        directories:
          - "/Users/travis/Library/Caches/go-build"
  # - os: windows
  #   go: 1.12.x
before_install:
  # Setup directory for binaries
  - mkdir ./bin
  - export PATH=$PATH:$PWD/bin
  # Misspell
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O misspell.tar.gz https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_linux_64bit.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O misspell.tar.gz https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_mac_64bit.tar.gz; fi
  - tar xf misspell.tar.gz && cp ./misspell ./bin/misspell
  # staticcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O staticcheck.tar.gz https://github.com/dominikh/go-tools/releases/download/2019.2.2/staticcheck_linux_amd64.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O staticcheck.tar.gz https://github.com/dominikh/go-tools/releases/download/2019.2.2/staticcheck_darwin_amd64.tar.gz; fi
  - tar xf staticcheck.tar.gz && cp ./staticcheck/staticcheck ./bin/staticcheck
  # golint
  - go get -u golang.org/x/lint/golint
  # gocyclo
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O ./bin/gocyclo https://github.com/adamdecaf/gocyclo/releases/download/2019-08-09/gocyclo-linux-amd64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O ./bin/gocyclo https://github.com/adamdecaf/gocyclo/releases/download/2019-08-09/gocyclo-darwin-amd64; fi
  - chmod +x ./bin/gocyclo
before_script:
  - GOFILES=$(find . -type f -name '*.go' | grep -v client)
  - go mod graph
script:
  # Just check gofmt on linux, it's the fastest builder
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -z $(gofmt -s -l $GOFILES); fi
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - misspell -error -locale US $GOFILES
  - gocyclo -over 50 $GOFILES
  - golint -set_exit_status $GOFILES
  - staticcheck ./cmd/... .
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y mingw; export PATH=/c/tools/mingw64/bin:"$PATH";fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make
  - make client
  - make docker
before_deploy:
  - make dist
after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push
deploy:
  provider: releases
  api_key:
    secure: vFMBg3YPUg8oux3TrIQ+AbX6dfs+jHXeDcTjOGyZO+HCScFiz8A/7JvKbWkFaUZPIRcDeHAKqJT/iV98vxS724m1DZU71YxOzbt8+j73hXqVMqOvcvoB/XZL+9yjfxGHqMN6V3R2WvAFULWmmRlxZBV7KEB9ME1dCEOjaa+Iu5pWfl5pa+IFr/wUOPvHUt+PTBAAvGXrd1ATbS0DKRkw6GzFUujZB251ATqECbz1GBVmiaZrwTg/g4inj4toOuxammm5pgJvVxkVGLGh7zJ2V5K0IsYcrH52IEWlkIbCK+VlpeL8rNZHjKpTrw3uo09mT67kcmGmmYboMR7aw8DjgB964QWzV3MLN+rC6oN+iuYQ2s7yNVtVnUgWREbt2nIEY14ikz4zbBGRLe1AJIGxVQxIDCb86JUpGXvq9lJ53BS7JG1MmcwnqILRsjAbITO6NCHpfofHjatkdarL3aTPDGdKhKVwVQN7/2CvDoUOzTL7sRmXxmVL5flQRbOqIsO6Bv/7MjshyuEUz9G6q1eiBkEnBvSUQ9JSNfYn/z0SwpOCyVGnkoCtk+zNOpR5rOClmZrcB6uZR1ZMkmovjThiLladTs/kDRvuIEJgM35krzJuCHSQuK/3nFm1fDYFARw9sT+g/OR/1OuoDtI7/HRDOzExojRspUUeNG/1paIOHUA=
  file_glob: true
  file:
    - bin/imagecashletter-*
  on:
    repo: moov-io/imagecashletter
    tags: true
    go: 1.12.x
  skip_cleanup: true
notifications:
  slack:
    secure: gZBYPH1MBi4D8Hq+knLt4NmaRwQwmyddVRX3/EVpg0teQuZr1pjuM8EV2EeKWZ4saurj4tAX4vEdEmAu+oT5vfqYiUxGbGqphtEx52wdpRHuRXHx58p04/hqg2M5iqMz2rFgkPtM2iNwC+fpzzyQ7DTYY4Iua/eF9cxb8NsshCBuVFWcg+z8vZfTzQvKnT2UkekoOL1VQ0bAc97//1a7cXkr/GPhyUGCzt9KUgCFnB5PE0je/fwWF27fV/FiuaQZ/cHFCFQkWdcp7zEwjPkDXrDx7gIAYYsje9OB5hNSRYE8UZiddKUjmb60YAQxmO7cms/9XnmCZKifsYZzeMCHujLzOT+Cy21yRghM5HfTHUxhm/MANPY5hxkrd511nXAs5IfyhS9ZmxhA+WPo5bzpcIimGbxv1Fc6cBh5zvIN4vPLGDpvZR9DaxqHJ0WfiHW85abqsPuiCW12oY4WZkD1Kbs0OsJLEeMWrIICgD4CoHkUJTeUQSnQDguNcK/yvtnih8E9BtcxjU9IrJ5sIQ+UJvptvLf30QIFDqeJ2di3L4vuop7fqDNGtI5L0V6YFoxME1ddguDRrn655qLnmWOXHO3vAXQIIdfidkG/kYZXASuQezfqCn1f9fRWjB/2RDdKPyYPJ1YQl7bCdAuyq36CRzt7Kb523f40K4XmaLsE13M=
